<<<<<<< HEAD
=======

>>>>>>> cc6b8a88d396801da738eba7f6c61e9bd82eb9e9
CREATE DATABASE BoCuuDe
Use BoCuuDe
CREATE TABLE GIASUC(
   ID   INT              NOT NULL,
   TENGIASUC VARCHAR (255)     NOT NULL,
   SOLUONG  INT             NOT NULL,   
   PRIMARY KEY (ID)
);
INSERT INTO GIASUC (ID, TENGIASUC, SOLUONG)
VALUES (1, 'Bo', 10);
INSERT INTO GIASUC (ID, TENGIASUC, SOLUONG)
VALUES (2, 'Cuu', 10);
INSERT INTO GIASUC (ID, TENGIASUC, SOLUONG)
VALUES (3, 'De', 10);
<<<<<<< HEAD
=======

CREATE DATABASE BoCuuDe
Use BoCuuDe
CREATE TABLE GIASUC(
   ID   INT              NOT NULL,
   TENGIASUC VARCHAR (255)     NOT NULL,
   SOLUONG  INT             NOT NULL,   
   PRIMARY KEY (ID)
);
INSERT INTO GIASUC (ID, TENGIASUC, SOLUONG)
VALUES (1, 'Bo', 10);
INSERT INTO GIASUC (ID, TENGIASUC, SOLUONG)
VALUES (2, 'Cuu', 10);
INSERT INTO GIASUC (ID, TENGIASUC, SOLUONG)
VALUES (3, 'De', 10);

>>>>>>> cc6b8a88d396801da738eba7f6c61e9bd82eb9e9
